---
driver:
  name: vagrant
  customize:
    memory: 8048
    cpus: 4

provisioner:
  name: chef_solo

platforms:
  - name: 'mwrock/Windows2012R2'
    transport:
      name: winrm
suites:
  - name: default
    run_list:
      - ['recipe[hyperv-cookbook::create]']
    attributes:
      hyperv:
        name: "TestVM"
        switch: "VLAN.Trunk.Virtual"
        create:
          vm_list = [
            {
              "name" => "TestVM1",
              "memory" => "8GB",
              "source_vhd" => "http://qwewqe"
              "destination_vhd" => "C:\\Hyper-V\\HVTest\\disk.vhd"
            },
            {
              "name" => "TestVM2",
              "memory" => "8 GB",
              "vhd" => "C:\\Hyper-V\\HVTest\\disk.vhd"
            }
          ]
        shutdown:
          force: true
